version: "3.9"

services:
  app:
    image: be-hse-monitoring:1.0.0
    container_name: cont-be-hse-monitoring
    command: uv run fastapi dev main.py --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"
