version: "3.9"

services:
  app:
    image: be-hse-monitoring:1.0.0
    container_name: cont-be-hse-monitoring
    restart: always
    command: uv run fastapi run main.py --host 0.0.0.0 --port 8001
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - mediamtx
      - minio
    networks:
      - hse-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: cont-mediamtx
    env_file:
      - .env
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=${WEBRTC}
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    ports:
      - "8554:8554"   # RTSP
      - "1935:1935"   # RTMP
      - "8888:8888"   # HLS
      - "8889:8889"   # WebRTC (HTTP)
      - "8890:8890/udp" # WebRTC (UDP)
      - "9997:9997"   # API
    networks:
      - hse-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio:latest
    container_name: cont-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    networks:
      - hse-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  hse-network:
    driver: bridge

volumes:
  minio_data:
